FROM python:3.8

RUN apt update
RUN apt install python3-pip -y
RUN pip3 install --upgrade pip
RUN pip3 install flask
RUN pip3 install requests
RUN pip3 install google_auth_oauthlib
RUN pip3 install flask_sqlalchemy

WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/requirements.txt
COPY client_secret.json /usr/src/app/client_secret.json

COPY ./TodoList.py /usr/src/app

CMD ["python", "./TodoList.py"]
